spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_crud
    username: root
    password: root
  jpa:
    database: MYSQL
    hibernate:
        ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: irwingcorrea.dev@gmail.com
    password: jsuz fqzy riqv aqfy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true